2024-09-02 06:12:25,940:DEBUG:certbot._internal.main:certbot version: 2.11.0
2024-09-02 06:12:25,940:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-09-02 06:12:25,940:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/certbot', '--email', 'putra.sembada@atmsolutions.id', '--agree-tos', '--no-eff-email', '-d', 'mighty-foxes-count-knowlingly.a276.dcdg.xyz']
2024-09-02 06:12:25,941:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-09-02 06:12:25,958:DEBUG:certbot._internal.log:Root logging level set at 30
2024-09-02 06:12:25,959:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2024-09-02 06:12:25,959:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f7cff0cb950>
Prep: True
2024-09-02 06:12:25,960:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f7cff0cb950> and installer None
2024-09-02 06:12:25,960:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2024-09-02 06:12:26,025:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/1923763256', new_authzr_uri=None, terms_of_service=None), cea2107068c0896b3d9dc2a9f2ae0d01, Meta(creation_dt=datetime.datetime(2024, 9, 2, 4, 22, 40, tzinfo=<UTC>), creation_host='d73636b0ed35', register_to_eff=None))>
2024-09-02 06:12:26,025:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-09-02 06:12:26,028:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-09-02 06:12:26,568:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 746
2024-09-02 06:12:26,569:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Sep 2024 06:12:26 GMT
Content-Type: application/json
Content-Length: 746
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "ITcwxjBRgRc": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-09-02 06:12:26,570:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for mighty-foxes-count-knowlingly.a276.dcdg.xyz
2024-09-02 06:12:26,577:DEBUG:acme.client:Requesting fresh nonce
2024-09-02 06:12:26,577:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-09-02 06:12:26,761:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2024-09-02 06:12:26,762:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Sep 2024 06:12:26 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: LTxuIrHNrFmtwYi3-w8yUPhk9ZE4_JmO7vUNaNjfwNEv9NiEqzk
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-09-02 06:12:26,762:DEBUG:acme.client:Storing nonce: LTxuIrHNrFmtwYi3-w8yUPhk9ZE4_JmO7vUNaNjfwNEv9NiEqzk
2024-09-02 06:12:26,762:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "mighty-foxes-count-knowlingly.a276.dcdg.xyz"\n    }\n  ]\n}'
2024-09-02 06:12:26,765:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTkyMzc2MzI1NiIsICJub25jZSI6ICJMVHh1SXJITnJGbXR3WWkzLXc4eVVQaGs5WkU0X0ptTzd2VU5hTmpmd05FdjlOaUVxemsiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "pULlWO0QTatCSVHomjYbL4x38txwxSnBSAbEZEjVfXZc16LBiaTN7rlcRHLPqwK_sRAwHc5vF2fa9Orq_Bo5YpzB0xQxUOhHMdaQJOh0Pr-dEFRipQZgx-xYqq4knkQt2vXianiiMLbnPa6RvPQrsQqKWT1Lm_0NRzHul7L7QJ6YPaRMZrrud4VFB9FZ3NTQ22Xd5Eo-uA3CMvM4ANfJDjYUEpokQSEmIYPJopAL_X7fdFdDYElEnOxRJFyj_zsM0tT55kZOZSQcAymE57u_BoZWe_CzKwa_peh-RrZZKA7vESu7WOsIajFeUInTBj0puv3wzT25beIKLLw0Ang1uQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogIm1pZ2h0eS1mb3hlcy1jb3VudC1rbm93bGluZ2x5LmEyNzYuZGNkZy54eXoiCiAgICB9CiAgXQp9"
}
2024-09-02 06:12:27,158:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 369
2024-09-02 06:12:27,158:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Mon, 02 Sep 2024 06:12:27 GMT
Content-Type: application/json
Content-Length: 369
Connection: keep-alive
Boulder-Requester: 1923763256
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/1923763256/301574754216
Replay-Nonce: LTxuIrHN1CZcsMIRsHQ9mjUuS8I4DTglmL5pYzInx6y0wTdsAOY
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2024-09-09T06:12:26Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "mighty-foxes-count-knowlingly.a276.dcdg.xyz"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/398265884166"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/1923763256/301574754216"
}
2024-09-02 06:12:27,158:DEBUG:acme.client:Storing nonce: LTxuIrHN1CZcsMIRsHQ9mjUuS8I4DTglmL5pYzInx6y0wTdsAOY
2024-09-02 06:12:27,159:DEBUG:acme.client:JWS payload:
b''
2024-09-02 06:12:27,160:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/398265884166:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTkyMzc2MzI1NiIsICJub25jZSI6ICJMVHh1SXJITjFDWmNzTUlSc0hROW1qVXVTOEk0RFRnbG1MNXBZeklueDZ5MHdUZHNBT1kiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzM5ODI2NTg4NDE2NiJ9",
  "signature": "QwBRTo6WYahBAV3acYhOECTNHGe0G6SRumAyZhY4BYbZf5r5k_3uHGSYifyRrnDJUPRWjzildZihf_zol9mlBG9fFuOUDqMtouOqk7DeOCzpcLLSR3eSjWNHp2UX_cIEj-X-eFk6vrjeNKknzODVNgNvjR5txA16y8GJnaPRbZaz4MCW6-6nMqlAahwV9EDZ19X9P6Z29fbwUmei5F8Z0z5FNMAjnYIg5dtf4Bv-HEvOBVgFG0_T_8-VUUHqewtVRms-HpPMyFHJUHhKCWrAnHHCrWDvyoiDZlu7HXiLhbAHNdUJoMBzcXRe1dNrp30L4tqbRYEp0ETT5_GKD_HdwA",
  "payload": ""
}
2024-09-02 06:12:27,371:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/398265884166 HTTP/1.1" 200 827
2024-09-02 06:12:27,371:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Sep 2024 06:12:27 GMT
Content-Type: application/json
Content-Length: 827
Connection: keep-alive
Boulder-Requester: 1923763256
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: LTxuIrHN53aVIu_pgnUqH1lZDvLU1fIhpGJ2HgVm35Mh5FOXcM0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "mighty-foxes-count-knowlingly.a276.dcdg.xyz"
  },
  "status": "pending",
  "expires": "2024-09-09T06:12:26Z",
  "challenges": [
    {
      "type": "tls-alpn-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/398265884166/UVJfwQ",
      "status": "pending",
      "token": "Px5KUVQriBSn1ybk6xodX0vGaYspX9BaGOljrydxQmU"
    },
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/398265884166/0Pvu8g",
      "status": "pending",
      "token": "Px5KUVQriBSn1ybk6xodX0vGaYspX9BaGOljrydxQmU"
    },
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/398265884166/ucJ6ng",
      "status": "pending",
      "token": "Px5KUVQriBSn1ybk6xodX0vGaYspX9BaGOljrydxQmU"
    }
  ]
}
2024-09-02 06:12:27,371:DEBUG:acme.client:Storing nonce: LTxuIrHN53aVIu_pgnUqH1lZDvLU1fIhpGJ2HgVm35Mh5FOXcM0
2024-09-02 06:12:27,372:INFO:certbot._internal.auth_handler:Performing the following challenges:
2024-09-02 06:12:27,372:INFO:certbot._internal.auth_handler:http-01 challenge for mighty-foxes-count-knowlingly.a276.dcdg.xyz
2024-09-02 06:12:27,372:INFO:certbot._internal.plugins.webroot:Using the webroot path /var/www/certbot for all unmatched domains.
2024-09-02 06:12:27,372:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /var/www/certbot/.well-known/acme-challenge
2024-09-02 06:12:27,374:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /var/www/certbot/.well-known/acme-challenge/Px5KUVQriBSn1ybk6xodX0vGaYspX9BaGOljrydxQmU
2024-09-02 06:12:27,374:DEBUG:acme.client:JWS payload:
b'{}'
2024-09-02 06:12:27,376:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/398265884166/ucJ6ng:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTkyMzc2MzI1NiIsICJub25jZSI6ICJMVHh1SXJITjUzYVZJdV9wZ25VcUgxbFpEdkxVMWZJaHBHSjJIZ1ZtMzVNaDVGT1hjTTAiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLXYzLzM5ODI2NTg4NDE2Ni91Y0o2bmcifQ",
  "signature": "UWa0OBgw8zGRAXZbb7orpMeDXh_J19Fv9OVm5Bi7foNQAA5qo_nLnOtVreyR2l4bCT-_OSEIm4RbDca0oiMp0DVnLtyIiaXkS9Tf-yIM7wJbNuH50zTk-K-ieOrglzt7A-A56lMMrM3Pck0j2JKzn-AH3xOeRwqGVklhfHMBMQ8Xt5uy8GBHNTgdA6HlhzUnsV1qIlOWmsfVrUdDLyp229rHAE21QpDrnPLwQdeOklb_pV4gC7URnATC4a5u-Rv11C-WCz4rtLiLh5xiLyL0tUVLkrxLYxbLrGeS3sGAYlXg8PLJtuANpuKm8wrmAsqM8JN4ZGc21MDHFmGFOCZb4g",
  "payload": "e30"
}
2024-09-02 06:12:27,577:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/398265884166/ucJ6ng HTTP/1.1" 200 187
2024-09-02 06:12:27,577:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Sep 2024 06:12:27 GMT
Content-Type: application/json
Content-Length: 187
Connection: keep-alive
Boulder-Requester: 1923763256
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/398265884166>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/398265884166/ucJ6ng
Replay-Nonce: LTxuIrHNKVKJ1u8eo_JeHSq3WKyLsHCJuQIF4ciU4vMlIwzLz3U
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/398265884166/ucJ6ng",
  "status": "pending",
  "token": "Px5KUVQriBSn1ybk6xodX0vGaYspX9BaGOljrydxQmU"
}
2024-09-02 06:12:27,578:DEBUG:acme.client:Storing nonce: LTxuIrHNKVKJ1u8eo_JeHSq3WKyLsHCJuQIF4ciU4vMlIwzLz3U
2024-09-02 06:12:27,578:INFO:certbot._internal.auth_handler:Waiting for verification...
2024-09-02 06:12:28,578:DEBUG:acme.client:JWS payload:
b''
2024-09-02 06:12:28,580:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/398265884166:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTkyMzc2MzI1NiIsICJub25jZSI6ICJMVHh1SXJITktWS0oxdThlb19KZUhTcTNXS3lMc0hDSnVRSUY0Y2lVNHZNbEl3ekx6M1UiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzM5ODI2NTg4NDE2NiJ9",
  "signature": "SOA5Jwf2O9VBGhPLfMEY1W5fcQMgMO_ZI7f-2iO06_wPY9z5nFmGfqlNYYeVq0iquecOVoRiZ_uJKyBnyZhdASeiCqg6LOOaiA-nmYMJsHYy_SnYAZ-LY-c6EDtG-P9ZLaGRRSwGBbVXBZaMkVyUaSyJaVHAkNxaqXm05-OWloE54o9SxlhFzT8O9Mdj3Y-blabzo5XS-lroauMbIrknEeZJ-VXBnWiVM73yVkgKNddTQStwNl5n4cHyelNOKI4Sr38k6YD4Qz8dNBSGeZZKwHxKdkaalndks6mf_tDdgeb-C3dPqFbn-BU-uYxVcUwrCjwOLuMm2b_eWy7zfEsFyg",
  "payload": ""
}
2024-09-02 06:12:28,778:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/398265884166 HTTP/1.1" 200 1137
2024-09-02 06:12:28,778:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Sep 2024 06:12:28 GMT
Content-Type: application/json
Content-Length: 1137
Connection: keep-alive
Boulder-Requester: 1923763256
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: JgybCyl7Syqe90RtKeoxgehqXD8Y0PKISwlQ8GyuydKEnNLZsvU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "mighty-foxes-count-knowlingly.a276.dcdg.xyz"
  },
  "status": "invalid",
  "expires": "2024-09-09T06:12:26Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/398265884166/ucJ6ng",
      "status": "invalid",
      "validated": "2024-09-02T06:12:27Z",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "3.106.99.236: Fetching http://mighty-foxes-count-knowlingly.a276.dcdg.xyz/.well-known/acme-challenge/Px5KUVQriBSn1ybk6xodX0vGaYspX9BaGOljrydxQmU: Connection refused",
        "status": 400
      },
      "token": "Px5KUVQriBSn1ybk6xodX0vGaYspX9BaGOljrydxQmU",
      "validationRecord": [
        {
          "url": "http://mighty-foxes-count-knowlingly.a276.dcdg.xyz/.well-known/acme-challenge/Px5KUVQriBSn1ybk6xodX0vGaYspX9BaGOljrydxQmU",
          "hostname": "mighty-foxes-count-knowlingly.a276.dcdg.xyz",
          "port": "80",
          "addressesResolved": [
            "3.106.99.236"
          ],
          "addressUsed": "3.106.99.236"
        }
      ]
    }
  ]
}
2024-09-02 06:12:28,778:DEBUG:acme.client:Storing nonce: JgybCyl7Syqe90RtKeoxgehqXD8Y0PKISwlQ8GyuydKEnNLZsvU
2024-09-02 06:12:28,779:INFO:certbot._internal.auth_handler:Challenge failed for domain mighty-foxes-count-knowlingly.a276.dcdg.xyz
2024-09-02 06:12:28,779:INFO:certbot._internal.auth_handler:http-01 challenge for mighty-foxes-count-knowlingly.a276.dcdg.xyz
2024-09-02 06:12:28,779:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: mighty-foxes-count-knowlingly.a276.dcdg.xyz
  Type:   connection
  Detail: 3.106.99.236: Fetching http://mighty-foxes-count-knowlingly.a276.dcdg.xyz/.well-known/acme-challenge/Px5KUVQriBSn1ybk6xodX0vGaYspX9BaGOljrydxQmU: Connection refused

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2024-09-02 06:12:28,780:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2024-09-02 06:12:28,780:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-09-02 06:12:28,780:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-09-02 06:12:28,780:DEBUG:certbot._internal.plugins.webroot:Removing /var/www/certbot/.well-known/acme-challenge/Px5KUVQriBSn1ybk6xodX0vGaYspX9BaGOljrydxQmU
2024-09-02 06:12:28,781:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2024-09-02 06:12:28,781:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2024-09-02 06:12:28,784:ERROR:certbot._internal.log:Some challenges have failed.
